diffusion:
  num_steps: 1000
  scheduler: linear

training:
  batch_size: 2
  learning_rate: 0.0001
  num_epochs: 10

data:
  dataset: mnist
  img_size: 64

logging:
  log_dir: runs
  save_dir: models

sampling:
  num_sample_imgs: 6
  save_dir: generated
  model_path: models\2024_05_26_17_00\best_model_ep12.pth