diffusion:
  num_steps: 200
  scheduler: linear

training:
  batch_size: 128
  learning_rate: 0.0002
  num_epochs: 30

data:
  dataset: mnist
  img_size: 64

logging:
  log_dir: runs
  save_dir: models

sampling:
  num_sample_imgs: 5x5
  save_dir: generated
  model_path: models\2024_05_27_10_00\best_model_ep1.pth